### ISSUE TITLE
Is it possible to create Sim3d object from a 4x4 matrix?

### ISSUE THREAD

**Issue by vincent-hui** [strasdat/Sophus#135] opened 2018-01-19 11:10 UTC
I see in Sim3Group there is a contructor taking a Matrix<Scalar,4,4>

  inline explicit
  Sim3Group(const Eigen::Matrix<Scalar,4,4>& T)
    : rxso3_(T.template topLeftCorner<3,3>()),
      translation_(T.template block<3,1>(0,3)) {
  }

I got a compilation error when I compile the following code fragment. The error message is "/opt/ros/kinetic/include/sophus/rxso3.hpp:643: error: ‘setScaledRotationMatrix’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
     setScaledRotationMatrix(sR);"
                            ^

#include <iostream>
#include <unsupported/Eigen/MatrixFunctions>
#include <sophus/sim3.hpp>

int main()
{
    Eigen::Matrix<double, 4, 4> I = Eigen::Matrix<double, 4, 4>::Identity();
    std::cout << I << '\n';
    std::cout << '\n';
    Sophus::Sim3d homoTrans;
    std::cout << homoTrans.matrix() << '\n';
    Sophus::Sim3d m2(I);
}

Is it possible to create Sim3d object from a 4x4 matrix?

**Comment by strasdat** [comment] 2018-01-19 21:06
I could not reproduce this issue you are seeing. In particular, this is covered by unit test:

https://github.com/strasdat/Sophus/blob/master/test/core/test_sim3.cpp#L173

Are you using the latest version of Sophus from origin/master?

**Comment by vincent-hui** [comment] 2018-01-20 09:06
I used ros-sophus package. I can reproduce this issue by using ros-sophus package.
Thanks, I tried latest version of Sophus from origin/master. I cannot reproduce this issue. I can create a Sim3d object from a 4x4 matrix.

**Comment by strasdat** [comment] 2018-01-22 05:16
Okay, thanks for the update. I'll close this issue,

**Closed by strasdat** 2018-01-22 05:16 UTC
